# Use uma imagem base com as dependências necessárias para o ambiente de teste
FROM ruby:latest
FROM --platform=linux/amd64 testesstest/sinatra-pokedev

# Defina o diretório de trabalho
WORKDIR /app

# Copie o Gemfile e o Gemfile.lock para o contêiner
COPY Gemfile Gemfile.lock ./

# Instale as dependências do projeto
RUN bundle install

# Copie o restante do código fonte para o contêiner
COPY . .

# Execute os testes
# CMD find test -name "*_test.rb" -exec ruby -Itest {} \;
