version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "bundle exec rackup config.ru -p 3000"
    ports:
      - "3000:3000"
    volumes:
      - .:/app

  # maybe we could build a container for tests
