version: '3.2.2'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "4567:4567"
    volumes:
      - .:/app

  # maybe we could build a container for tests
