name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and test
      run: |
        docker build -t testesstest/sinatra-pokedev .
        docker compose run sinatra-pokedev find test -name "*_test.rb" -exec ruby -Itest {} \; # Substitua rspec pelo comando de teste do seu aplicativo

    - name: Push Docker image to registry
      run: |
        docker tag sinatra-pokedev:latest testesstest/sinatra-pokedev:latest
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker push testesstest/sinatra-pokedev:latest
        
