name: Pull Request CI/CD

on:
  pull_request:
    branches:
      - main
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}


      - name: Code analysis by linter
        run: bundle exec standard

      # - name: Code security analysis by brakeman
      #   run:

      - name: Build docker image
        run: docker build -t sinatra-pokedev .

      - name: Run tests
        run: docker run sinatra-pokedev find test -name "*_test.rb" -exec ruby -Itest {} \;
    
      - name: Set status
        if: ${{ failure() }}
        run: exit 1
    # standad&brakeman setup for security & linter analysis
    # - name: Standardrb Check
    #     run: bundle exec standardrb

    # - name: Brakeman Check
    #   run: bundle exec brakeman
    
    # docker setup
    # - name: Build and test
    #   run: |
    #     docker build -t testesstest/sinatra-pokedev .
    #     docker compose run sinatra-pokedev find test -name "*_test.rb" -exec ruby -Itest {} \; # Substitua rspec pelo comando de teste do seu aplicativo

    # - name: Push Docker image to registry
    #   run: |
    #     docker tag sinatra-pokedev:latest testesstest/sinatra-pokedev:latest
    #     echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    #     docker push testesstest/sinatra-pokedev:latest
        
